// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xsoftmax.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XSoftmax_CfgInitialize(XSoftmax *InstancePtr, XSoftmax_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_BaseAddress = ConfigPtr->Control_BaseAddress;
    InstancePtr->Input_BaseAddress = ConfigPtr->Input_BaseAddress;
    InstancePtr->Output_BaseAddress = ConfigPtr->Output_BaseAddress;
    InstancePtr->Parameter_BaseAddress = ConfigPtr->Parameter_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XSoftmax_Start(XSoftmax *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSoftmax_ReadReg(InstancePtr->Control_BaseAddress, XSOFTMAX_CONTROL_ADDR_AP_CTRL) & 0x80;
    XSoftmax_WriteReg(InstancePtr->Control_BaseAddress, XSOFTMAX_CONTROL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XSoftmax_IsDone(XSoftmax *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSoftmax_ReadReg(InstancePtr->Control_BaseAddress, XSOFTMAX_CONTROL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XSoftmax_IsIdle(XSoftmax *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSoftmax_ReadReg(InstancePtr->Control_BaseAddress, XSOFTMAX_CONTROL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XSoftmax_IsReady(XSoftmax *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSoftmax_ReadReg(InstancePtr->Control_BaseAddress, XSOFTMAX_CONTROL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XSoftmax_EnableAutoRestart(XSoftmax *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSoftmax_WriteReg(InstancePtr->Control_BaseAddress, XSOFTMAX_CONTROL_ADDR_AP_CTRL, 0x80);
}

void XSoftmax_DisableAutoRestart(XSoftmax *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSoftmax_WriteReg(InstancePtr->Control_BaseAddress, XSOFTMAX_CONTROL_ADDR_AP_CTRL, 0);
}

u32 XSoftmax_Get_mem_block2_dense_BaseAddress(XSoftmax *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Input_BaseAddress + XSOFTMAX_INPUT_ADDR_MEM_BLOCK2_DENSE_BASE);
}

u32 XSoftmax_Get_mem_block2_dense_HighAddress(XSoftmax *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Input_BaseAddress + XSOFTMAX_INPUT_ADDR_MEM_BLOCK2_DENSE_HIGH);
}

u32 XSoftmax_Get_mem_block2_dense_TotalBytes(XSoftmax *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XSOFTMAX_INPUT_ADDR_MEM_BLOCK2_DENSE_HIGH - XSOFTMAX_INPUT_ADDR_MEM_BLOCK2_DENSE_BASE + 1);
}

u32 XSoftmax_Get_mem_block2_dense_BitWidth(XSoftmax *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSOFTMAX_INPUT_WIDTH_MEM_BLOCK2_DENSE;
}

u32 XSoftmax_Get_mem_block2_dense_Depth(XSoftmax *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSOFTMAX_INPUT_DEPTH_MEM_BLOCK2_DENSE;
}

u32 XSoftmax_Write_mem_block2_dense_Words(XSoftmax *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XSOFTMAX_INPUT_ADDR_MEM_BLOCK2_DENSE_HIGH - XSOFTMAX_INPUT_ADDR_MEM_BLOCK2_DENSE_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Input_BaseAddress + XSOFTMAX_INPUT_ADDR_MEM_BLOCK2_DENSE_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XSoftmax_Read_mem_block2_dense_Words(XSoftmax *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XSOFTMAX_INPUT_ADDR_MEM_BLOCK2_DENSE_HIGH - XSOFTMAX_INPUT_ADDR_MEM_BLOCK2_DENSE_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Input_BaseAddress + XSOFTMAX_INPUT_ADDR_MEM_BLOCK2_DENSE_BASE + (offset + i)*4);
    }
    return length;
}

u32 XSoftmax_Write_mem_block2_dense_Bytes(XSoftmax *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XSOFTMAX_INPUT_ADDR_MEM_BLOCK2_DENSE_HIGH - XSOFTMAX_INPUT_ADDR_MEM_BLOCK2_DENSE_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Input_BaseAddress + XSOFTMAX_INPUT_ADDR_MEM_BLOCK2_DENSE_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XSoftmax_Read_mem_block2_dense_Bytes(XSoftmax *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XSOFTMAX_INPUT_ADDR_MEM_BLOCK2_DENSE_HIGH - XSOFTMAX_INPUT_ADDR_MEM_BLOCK2_DENSE_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Input_BaseAddress + XSOFTMAX_INPUT_ADDR_MEM_BLOCK2_DENSE_BASE + offset + i);
    }
    return length;
}

u32 XSoftmax_Get_class_BaseAddress(XSoftmax *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Output_BaseAddress + XSOFTMAX_OUTPUT_ADDR_CLASS_BASE);
}

u32 XSoftmax_Get_class_HighAddress(XSoftmax *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Output_BaseAddress + XSOFTMAX_OUTPUT_ADDR_CLASS_HIGH);
}

u32 XSoftmax_Get_class_TotalBytes(XSoftmax *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XSOFTMAX_OUTPUT_ADDR_CLASS_HIGH - XSOFTMAX_OUTPUT_ADDR_CLASS_BASE + 1);
}

u32 XSoftmax_Get_class_BitWidth(XSoftmax *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSOFTMAX_OUTPUT_WIDTH_CLASS;
}

u32 XSoftmax_Get_class_Depth(XSoftmax *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSOFTMAX_OUTPUT_DEPTH_CLASS;
}

u32 XSoftmax_Write_class_Words(XSoftmax *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XSOFTMAX_OUTPUT_ADDR_CLASS_HIGH - XSOFTMAX_OUTPUT_ADDR_CLASS_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Output_BaseAddress + XSOFTMAX_OUTPUT_ADDR_CLASS_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XSoftmax_Read_class_Words(XSoftmax *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XSOFTMAX_OUTPUT_ADDR_CLASS_HIGH - XSOFTMAX_OUTPUT_ADDR_CLASS_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Output_BaseAddress + XSOFTMAX_OUTPUT_ADDR_CLASS_BASE + (offset + i)*4);
    }
    return length;
}

u32 XSoftmax_Write_class_Bytes(XSoftmax *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XSOFTMAX_OUTPUT_ADDR_CLASS_HIGH - XSOFTMAX_OUTPUT_ADDR_CLASS_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Output_BaseAddress + XSOFTMAX_OUTPUT_ADDR_CLASS_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XSoftmax_Read_class_Bytes(XSoftmax *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XSOFTMAX_OUTPUT_ADDR_CLASS_HIGH - XSOFTMAX_OUTPUT_ADDR_CLASS_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Output_BaseAddress + XSOFTMAX_OUTPUT_ADDR_CLASS_BASE + offset + i);
    }
    return length;
}

u32 XSoftmax_Get_result_BaseAddress(XSoftmax *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Output_BaseAddress + XSOFTMAX_OUTPUT_ADDR_RESULT_BASE);
}

u32 XSoftmax_Get_result_HighAddress(XSoftmax *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Output_BaseAddress + XSOFTMAX_OUTPUT_ADDR_RESULT_HIGH);
}

u32 XSoftmax_Get_result_TotalBytes(XSoftmax *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XSOFTMAX_OUTPUT_ADDR_RESULT_HIGH - XSOFTMAX_OUTPUT_ADDR_RESULT_BASE + 1);
}

u32 XSoftmax_Get_result_BitWidth(XSoftmax *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSOFTMAX_OUTPUT_WIDTH_RESULT;
}

u32 XSoftmax_Get_result_Depth(XSoftmax *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSOFTMAX_OUTPUT_DEPTH_RESULT;
}

u32 XSoftmax_Write_result_Words(XSoftmax *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XSOFTMAX_OUTPUT_ADDR_RESULT_HIGH - XSOFTMAX_OUTPUT_ADDR_RESULT_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Output_BaseAddress + XSOFTMAX_OUTPUT_ADDR_RESULT_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XSoftmax_Read_result_Words(XSoftmax *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XSOFTMAX_OUTPUT_ADDR_RESULT_HIGH - XSOFTMAX_OUTPUT_ADDR_RESULT_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Output_BaseAddress + XSOFTMAX_OUTPUT_ADDR_RESULT_BASE + (offset + i)*4);
    }
    return length;
}

u32 XSoftmax_Write_result_Bytes(XSoftmax *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XSOFTMAX_OUTPUT_ADDR_RESULT_HIGH - XSOFTMAX_OUTPUT_ADDR_RESULT_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Output_BaseAddress + XSOFTMAX_OUTPUT_ADDR_RESULT_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XSoftmax_Read_result_Bytes(XSoftmax *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XSOFTMAX_OUTPUT_ADDR_RESULT_HIGH - XSOFTMAX_OUTPUT_ADDR_RESULT_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Output_BaseAddress + XSOFTMAX_OUTPUT_ADDR_RESULT_BASE + offset + i);
    }
    return length;
}

u32 XSoftmax_Get_bd3_BaseAddress(XSoftmax *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Parameter_BaseAddress + XSOFTMAX_PARAMETER_ADDR_BD3_BASE);
}

u32 XSoftmax_Get_bd3_HighAddress(XSoftmax *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Parameter_BaseAddress + XSOFTMAX_PARAMETER_ADDR_BD3_HIGH);
}

u32 XSoftmax_Get_bd3_TotalBytes(XSoftmax *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XSOFTMAX_PARAMETER_ADDR_BD3_HIGH - XSOFTMAX_PARAMETER_ADDR_BD3_BASE + 1);
}

u32 XSoftmax_Get_bd3_BitWidth(XSoftmax *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSOFTMAX_PARAMETER_WIDTH_BD3;
}

u32 XSoftmax_Get_bd3_Depth(XSoftmax *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSOFTMAX_PARAMETER_DEPTH_BD3;
}

u32 XSoftmax_Write_bd3_Words(XSoftmax *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XSOFTMAX_PARAMETER_ADDR_BD3_HIGH - XSOFTMAX_PARAMETER_ADDR_BD3_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Parameter_BaseAddress + XSOFTMAX_PARAMETER_ADDR_BD3_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XSoftmax_Read_bd3_Words(XSoftmax *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XSOFTMAX_PARAMETER_ADDR_BD3_HIGH - XSOFTMAX_PARAMETER_ADDR_BD3_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Parameter_BaseAddress + XSOFTMAX_PARAMETER_ADDR_BD3_BASE + (offset + i)*4);
    }
    return length;
}

u32 XSoftmax_Write_bd3_Bytes(XSoftmax *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XSOFTMAX_PARAMETER_ADDR_BD3_HIGH - XSOFTMAX_PARAMETER_ADDR_BD3_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Parameter_BaseAddress + XSOFTMAX_PARAMETER_ADDR_BD3_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XSoftmax_Read_bd3_Bytes(XSoftmax *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XSOFTMAX_PARAMETER_ADDR_BD3_HIGH - XSOFTMAX_PARAMETER_ADDR_BD3_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Parameter_BaseAddress + XSOFTMAX_PARAMETER_ADDR_BD3_BASE + offset + i);
    }
    return length;
}

void XSoftmax_InterruptGlobalEnable(XSoftmax *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSoftmax_WriteReg(InstancePtr->Control_BaseAddress, XSOFTMAX_CONTROL_ADDR_GIE, 1);
}

void XSoftmax_InterruptGlobalDisable(XSoftmax *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSoftmax_WriteReg(InstancePtr->Control_BaseAddress, XSOFTMAX_CONTROL_ADDR_GIE, 0);
}

void XSoftmax_InterruptEnable(XSoftmax *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSoftmax_ReadReg(InstancePtr->Control_BaseAddress, XSOFTMAX_CONTROL_ADDR_IER);
    XSoftmax_WriteReg(InstancePtr->Control_BaseAddress, XSOFTMAX_CONTROL_ADDR_IER, Register | Mask);
}

void XSoftmax_InterruptDisable(XSoftmax *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSoftmax_ReadReg(InstancePtr->Control_BaseAddress, XSOFTMAX_CONTROL_ADDR_IER);
    XSoftmax_WriteReg(InstancePtr->Control_BaseAddress, XSOFTMAX_CONTROL_ADDR_IER, Register & (~Mask));
}

void XSoftmax_InterruptClear(XSoftmax *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSoftmax_WriteReg(InstancePtr->Control_BaseAddress, XSOFTMAX_CONTROL_ADDR_ISR, Mask);
}

u32 XSoftmax_InterruptGetEnabled(XSoftmax *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSoftmax_ReadReg(InstancePtr->Control_BaseAddress, XSOFTMAX_CONTROL_ADDR_IER);
}

u32 XSoftmax_InterruptGetStatus(XSoftmax *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSoftmax_ReadReg(InstancePtr->Control_BaseAddress, XSOFTMAX_CONTROL_ADDR_ISR);
}

