// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XVGG16_H
#define XVGG16_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xvgg16_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_BaseAddress;
    u32 Input_BaseAddress;
    u32 Output_BaseAddress;
    u32 Output1_BaseAddress;
    u32 Parameter_BaseAddress;
} XVgg16_Config;
#endif

typedef struct {
    u32 Control_BaseAddress;
    u32 Input_BaseAddress;
    u32 Output_BaseAddress;
    u32 Output1_BaseAddress;
    u32 Parameter_BaseAddress;
    u32 IsReady;
} XVgg16;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XVgg16_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XVgg16_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XVgg16_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XVgg16_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XVgg16_Initialize(XVgg16 *InstancePtr, u16 DeviceId);
XVgg16_Config* XVgg16_LookupConfig(u16 DeviceId);
int XVgg16_CfgInitialize(XVgg16 *InstancePtr, XVgg16_Config *ConfigPtr);
#else
int XVgg16_Initialize(XVgg16 *InstancePtr, const char* InstanceName);
int XVgg16_Release(XVgg16 *InstancePtr);
#endif

void XVgg16_Start(XVgg16 *InstancePtr);
u32 XVgg16_IsDone(XVgg16 *InstancePtr);
u32 XVgg16_IsIdle(XVgg16 *InstancePtr);
u32 XVgg16_IsReady(XVgg16 *InstancePtr);
void XVgg16_EnableAutoRestart(XVgg16 *InstancePtr);
void XVgg16_DisableAutoRestart(XVgg16 *InstancePtr);

u32 XVgg16_Get_mem_block2_dense_BaseAddress(XVgg16 *InstancePtr);
u32 XVgg16_Get_mem_block2_dense_HighAddress(XVgg16 *InstancePtr);
u32 XVgg16_Get_mem_block2_dense_TotalBytes(XVgg16 *InstancePtr);
u32 XVgg16_Get_mem_block2_dense_BitWidth(XVgg16 *InstancePtr);
u32 XVgg16_Get_mem_block2_dense_Depth(XVgg16 *InstancePtr);
u32 XVgg16_Write_mem_block2_dense_Words(XVgg16 *InstancePtr, int offset, int *data, int length);
u32 XVgg16_Read_mem_block2_dense_Words(XVgg16 *InstancePtr, int offset, int *data, int length);
u32 XVgg16_Write_mem_block2_dense_Bytes(XVgg16 *InstancePtr, int offset, char *data, int length);
u32 XVgg16_Read_mem_block2_dense_Bytes(XVgg16 *InstancePtr, int offset, char *data, int length);
u32 XVgg16_Get_class_BaseAddress(XVgg16 *InstancePtr);
u32 XVgg16_Get_class_HighAddress(XVgg16 *InstancePtr);
u32 XVgg16_Get_class_TotalBytes(XVgg16 *InstancePtr);
u32 XVgg16_Get_class_BitWidth(XVgg16 *InstancePtr);
u32 XVgg16_Get_class_Depth(XVgg16 *InstancePtr);
u32 XVgg16_Write_class_Words(XVgg16 *InstancePtr, int offset, int *data, int length);
u32 XVgg16_Read_class_Words(XVgg16 *InstancePtr, int offset, int *data, int length);
u32 XVgg16_Write_class_Bytes(XVgg16 *InstancePtr, int offset, char *data, int length);
u32 XVgg16_Read_class_Bytes(XVgg16 *InstancePtr, int offset, char *data, int length);
u32 XVgg16_Get_result_BaseAddress(XVgg16 *InstancePtr);
u32 XVgg16_Get_result_HighAddress(XVgg16 *InstancePtr);
u32 XVgg16_Get_result_TotalBytes(XVgg16 *InstancePtr);
u32 XVgg16_Get_result_BitWidth(XVgg16 *InstancePtr);
u32 XVgg16_Get_result_Depth(XVgg16 *InstancePtr);
u32 XVgg16_Write_result_Words(XVgg16 *InstancePtr, int offset, int *data, int length);
u32 XVgg16_Read_result_Words(XVgg16 *InstancePtr, int offset, int *data, int length);
u32 XVgg16_Write_result_Bytes(XVgg16 *InstancePtr, int offset, char *data, int length);
u32 XVgg16_Read_result_Bytes(XVgg16 *InstancePtr, int offset, char *data, int length);
u32 XVgg16_Get_bd3_BaseAddress(XVgg16 *InstancePtr);
u32 XVgg16_Get_bd3_HighAddress(XVgg16 *InstancePtr);
u32 XVgg16_Get_bd3_TotalBytes(XVgg16 *InstancePtr);
u32 XVgg16_Get_bd3_BitWidth(XVgg16 *InstancePtr);
u32 XVgg16_Get_bd3_Depth(XVgg16 *InstancePtr);
u32 XVgg16_Write_bd3_Words(XVgg16 *InstancePtr, int offset, int *data, int length);
u32 XVgg16_Read_bd3_Words(XVgg16 *InstancePtr, int offset, int *data, int length);
u32 XVgg16_Write_bd3_Bytes(XVgg16 *InstancePtr, int offset, char *data, int length);
u32 XVgg16_Read_bd3_Bytes(XVgg16 *InstancePtr, int offset, char *data, int length);

void XVgg16_InterruptGlobalEnable(XVgg16 *InstancePtr);
void XVgg16_InterruptGlobalDisable(XVgg16 *InstancePtr);
void XVgg16_InterruptEnable(XVgg16 *InstancePtr, u32 Mask);
void XVgg16_InterruptDisable(XVgg16 *InstancePtr, u32 Mask);
void XVgg16_InterruptClear(XVgg16 *InstancePtr, u32 Mask);
u32 XVgg16_InterruptGetEnabled(XVgg16 *InstancePtr);
u32 XVgg16_InterruptGetStatus(XVgg16 *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
