// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xdesne_reluflatten_softmax.h"

extern XDesne_reluflatten_softmax_Config XDesne_reluflatten_softmax_ConfigTable[];

XDesne_reluflatten_softmax_Config *XDesne_reluflatten_softmax_LookupConfig(u16 DeviceId) {
	XDesne_reluflatten_softmax_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XDESNE_RELUFLATTEN_SOFTMAX_NUM_INSTANCES; Index++) {
		if (XDesne_reluflatten_softmax_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XDesne_reluflatten_softmax_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XDesne_reluflatten_softmax_Initialize(XDesne_reluflatten_softmax *InstancePtr, u16 DeviceId) {
	XDesne_reluflatten_softmax_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XDesne_reluflatten_softmax_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XDesne_reluflatten_softmax_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

