// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// bias
// 0x4000 ~
// 0x7fff : Memory 'bd1' (4096 * 32b)
//          Word n : bit [31:0] - bd1[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDESNE_RELUFLATTEN_SOFTMAX_BIAS_ADDR_BD1_BASE 0x4000
#define XDESNE_RELUFLATTEN_SOFTMAX_BIAS_ADDR_BD1_HIGH 0x7fff
#define XDESNE_RELUFLATTEN_SOFTMAX_BIAS_WIDTH_BD1     32
#define XDESNE_RELUFLATTEN_SOFTMAX_BIAS_DEPTH_BD1     4096

// bias2
// 0x4000 ~
// 0x7fff : Memory 'bd2' (4096 * 32b)
//          Word n : bit [31:0] - bd2[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDESNE_RELUFLATTEN_SOFTMAX_BIAS2_ADDR_BD2_BASE 0x4000
#define XDESNE_RELUFLATTEN_SOFTMAX_BIAS2_ADDR_BD2_HIGH 0x7fff
#define XDESNE_RELUFLATTEN_SOFTMAX_BIAS2_WIDTH_BD2     32
#define XDESNE_RELUFLATTEN_SOFTMAX_BIAS2_DEPTH_BD2     4096

// bias3
// 0x1000 ~
// 0x1fff : Memory 'bd3' (1000 * 32b)
//          Word n : bit [31:0] - bd3[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDESNE_RELUFLATTEN_SOFTMAX_BIAS3_ADDR_BD3_BASE 0x1000
#define XDESNE_RELUFLATTEN_SOFTMAX_BIAS3_ADDR_BD3_HIGH 0x1fff
#define XDESNE_RELUFLATTEN_SOFTMAX_BIAS3_WIDTH_BD3     32
#define XDESNE_RELUFLATTEN_SOFTMAX_BIAS3_DEPTH_BD3     1000

// CONTROL
// 0x0 : Control signals
//       bit 0  - ap_start (Read/Write/COH)
//       bit 1  - ap_done (Read/COR)
//       bit 2  - ap_idle (Read)
//       bit 3  - ap_ready (Read)
//       bit 7  - auto_restart (Read/Write)
//       others - reserved
// 0x4 : Global Interrupt Enable Register
//       bit 0  - Global Interrupt Enable (Read/Write)
//       others - reserved
// 0x8 : IP Interrupt Enable Register (Read/Write)
//       bit 0  - Channel 0 (ap_done)
//       bit 1  - Channel 1 (ap_ready)
//       others - reserved
// 0xc : IP Interrupt Status Register (Read/TOW)
//       bit 0  - Channel 0 (ap_done)
//       bit 1  - Channel 1 (ap_ready)
//       others - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDESNE_RELUFLATTEN_SOFTMAX_CONTROL_ADDR_AP_CTRL 0x0
#define XDESNE_RELUFLATTEN_SOFTMAX_CONTROL_ADDR_GIE     0x4
#define XDESNE_RELUFLATTEN_SOFTMAX_CONTROL_ADDR_IER     0x8
#define XDESNE_RELUFLATTEN_SOFTMAX_CONTROL_ADDR_ISR     0xc

// INPUT
// 0x20000 ~
// 0x3ffff : Memory 'mem_block1_dense' (25088 * 32b)
//           Word n : bit [31:0] - mem_block1_dense[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDESNE_RELUFLATTEN_SOFTMAX_INPUT_ADDR_MEM_BLOCK1_DENSE_BASE 0x20000
#define XDESNE_RELUFLATTEN_SOFTMAX_INPUT_ADDR_MEM_BLOCK1_DENSE_HIGH 0x3ffff
#define XDESNE_RELUFLATTEN_SOFTMAX_INPUT_WIDTH_MEM_BLOCK1_DENSE     32
#define XDESNE_RELUFLATTEN_SOFTMAX_INPUT_DEPTH_MEM_BLOCK1_DENSE     25088

// OUTPUT
// 0x1000 ~
// 0x1fff : Memory 'class' (1000 * 32b)
//          Word n : bit [31:0] - class[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDESNE_RELUFLATTEN_SOFTMAX_OUTPUT_ADDR_CLASS_BASE 0x1000
#define XDESNE_RELUFLATTEN_SOFTMAX_OUTPUT_ADDR_CLASS_HIGH 0x1fff
#define XDESNE_RELUFLATTEN_SOFTMAX_OUTPUT_WIDTH_CLASS     32
#define XDESNE_RELUFLATTEN_SOFTMAX_OUTPUT_DEPTH_CLASS     1000

// OUTPUT1
// 0x1000 ~
// 0x1fff : Memory 'result' (1000 * 32b)
//          Word n : bit [31:0] - result[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDESNE_RELUFLATTEN_SOFTMAX_OUTPUT1_ADDR_RESULT_BASE 0x1000
#define XDESNE_RELUFLATTEN_SOFTMAX_OUTPUT1_ADDR_RESULT_HIGH 0x1fff
#define XDESNE_RELUFLATTEN_SOFTMAX_OUTPUT1_WIDTH_RESULT     32
#define XDESNE_RELUFLATTEN_SOFTMAX_OUTPUT1_DEPTH_RESULT     1000

