// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XDESNE_RELUFLATTEN_SOFTMAX_H
#define XDESNE_RELUFLATTEN_SOFTMAX_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xdesne_reluflatten_softmax_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Bias_BaseAddress;
    u32 Bias2_BaseAddress;
    u32 Bias3_BaseAddress;
    u32 Control_BaseAddress;
    u32 Input_BaseAddress;
    u32 Output_BaseAddress;
    u32 Output1_BaseAddress;
} XDesne_reluflatten_softmax_Config;
#endif

typedef struct {
    u32 Bias_BaseAddress;
    u32 Bias2_BaseAddress;
    u32 Bias3_BaseAddress;
    u32 Control_BaseAddress;
    u32 Input_BaseAddress;
    u32 Output_BaseAddress;
    u32 Output1_BaseAddress;
    u32 IsReady;
} XDesne_reluflatten_softmax;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XDesne_reluflatten_softmax_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XDesne_reluflatten_softmax_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XDesne_reluflatten_softmax_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XDesne_reluflatten_softmax_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XDesne_reluflatten_softmax_Initialize(XDesne_reluflatten_softmax *InstancePtr, u16 DeviceId);
XDesne_reluflatten_softmax_Config* XDesne_reluflatten_softmax_LookupConfig(u16 DeviceId);
int XDesne_reluflatten_softmax_CfgInitialize(XDesne_reluflatten_softmax *InstancePtr, XDesne_reluflatten_softmax_Config *ConfigPtr);
#else
int XDesne_reluflatten_softmax_Initialize(XDesne_reluflatten_softmax *InstancePtr, const char* InstanceName);
int XDesne_reluflatten_softmax_Release(XDesne_reluflatten_softmax *InstancePtr);
#endif

void XDesne_reluflatten_softmax_Start(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_IsDone(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_IsIdle(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_IsReady(XDesne_reluflatten_softmax *InstancePtr);
void XDesne_reluflatten_softmax_EnableAutoRestart(XDesne_reluflatten_softmax *InstancePtr);
void XDesne_reluflatten_softmax_DisableAutoRestart(XDesne_reluflatten_softmax *InstancePtr);

u32 XDesne_reluflatten_softmax_Get_bd1_BaseAddress(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Get_bd1_HighAddress(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Get_bd1_TotalBytes(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Get_bd1_BitWidth(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Get_bd1_Depth(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Write_bd1_Words(XDesne_reluflatten_softmax *InstancePtr, int offset, int *data, int length);
u32 XDesne_reluflatten_softmax_Read_bd1_Words(XDesne_reluflatten_softmax *InstancePtr, int offset, int *data, int length);
u32 XDesne_reluflatten_softmax_Write_bd1_Bytes(XDesne_reluflatten_softmax *InstancePtr, int offset, char *data, int length);
u32 XDesne_reluflatten_softmax_Read_bd1_Bytes(XDesne_reluflatten_softmax *InstancePtr, int offset, char *data, int length);
u32 XDesne_reluflatten_softmax_Get_bd2_BaseAddress(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Get_bd2_HighAddress(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Get_bd2_TotalBytes(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Get_bd2_BitWidth(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Get_bd2_Depth(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Write_bd2_Words(XDesne_reluflatten_softmax *InstancePtr, int offset, int *data, int length);
u32 XDesne_reluflatten_softmax_Read_bd2_Words(XDesne_reluflatten_softmax *InstancePtr, int offset, int *data, int length);
u32 XDesne_reluflatten_softmax_Write_bd2_Bytes(XDesne_reluflatten_softmax *InstancePtr, int offset, char *data, int length);
u32 XDesne_reluflatten_softmax_Read_bd2_Bytes(XDesne_reluflatten_softmax *InstancePtr, int offset, char *data, int length);
u32 XDesne_reluflatten_softmax_Get_bd3_BaseAddress(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Get_bd3_HighAddress(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Get_bd3_TotalBytes(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Get_bd3_BitWidth(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Get_bd3_Depth(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Write_bd3_Words(XDesne_reluflatten_softmax *InstancePtr, int offset, int *data, int length);
u32 XDesne_reluflatten_softmax_Read_bd3_Words(XDesne_reluflatten_softmax *InstancePtr, int offset, int *data, int length);
u32 XDesne_reluflatten_softmax_Write_bd3_Bytes(XDesne_reluflatten_softmax *InstancePtr, int offset, char *data, int length);
u32 XDesne_reluflatten_softmax_Read_bd3_Bytes(XDesne_reluflatten_softmax *InstancePtr, int offset, char *data, int length);
u32 XDesne_reluflatten_softmax_Get_mem_block1_dense_BaseAddress(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Get_mem_block1_dense_HighAddress(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Get_mem_block1_dense_TotalBytes(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Get_mem_block1_dense_BitWidth(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Get_mem_block1_dense_Depth(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Write_mem_block1_dense_Words(XDesne_reluflatten_softmax *InstancePtr, int offset, int *data, int length);
u32 XDesne_reluflatten_softmax_Read_mem_block1_dense_Words(XDesne_reluflatten_softmax *InstancePtr, int offset, int *data, int length);
u32 XDesne_reluflatten_softmax_Write_mem_block1_dense_Bytes(XDesne_reluflatten_softmax *InstancePtr, int offset, char *data, int length);
u32 XDesne_reluflatten_softmax_Read_mem_block1_dense_Bytes(XDesne_reluflatten_softmax *InstancePtr, int offset, char *data, int length);
u32 XDesne_reluflatten_softmax_Get_class_BaseAddress(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Get_class_HighAddress(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Get_class_TotalBytes(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Get_class_BitWidth(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Get_class_Depth(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Write_class_Words(XDesne_reluflatten_softmax *InstancePtr, int offset, int *data, int length);
u32 XDesne_reluflatten_softmax_Read_class_Words(XDesne_reluflatten_softmax *InstancePtr, int offset, int *data, int length);
u32 XDesne_reluflatten_softmax_Write_class_Bytes(XDesne_reluflatten_softmax *InstancePtr, int offset, char *data, int length);
u32 XDesne_reluflatten_softmax_Read_class_Bytes(XDesne_reluflatten_softmax *InstancePtr, int offset, char *data, int length);
u32 XDesne_reluflatten_softmax_Get_result_BaseAddress(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Get_result_HighAddress(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Get_result_TotalBytes(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Get_result_BitWidth(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Get_result_Depth(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_Write_result_Words(XDesne_reluflatten_softmax *InstancePtr, int offset, int *data, int length);
u32 XDesne_reluflatten_softmax_Read_result_Words(XDesne_reluflatten_softmax *InstancePtr, int offset, int *data, int length);
u32 XDesne_reluflatten_softmax_Write_result_Bytes(XDesne_reluflatten_softmax *InstancePtr, int offset, char *data, int length);
u32 XDesne_reluflatten_softmax_Read_result_Bytes(XDesne_reluflatten_softmax *InstancePtr, int offset, char *data, int length);

void XDesne_reluflatten_softmax_InterruptGlobalEnable(XDesne_reluflatten_softmax *InstancePtr);
void XDesne_reluflatten_softmax_InterruptGlobalDisable(XDesne_reluflatten_softmax *InstancePtr);
void XDesne_reluflatten_softmax_InterruptEnable(XDesne_reluflatten_softmax *InstancePtr, u32 Mask);
void XDesne_reluflatten_softmax_InterruptDisable(XDesne_reluflatten_softmax *InstancePtr, u32 Mask);
void XDesne_reluflatten_softmax_InterruptClear(XDesne_reluflatten_softmax *InstancePtr, u32 Mask);
u32 XDesne_reluflatten_softmax_InterruptGetEnabled(XDesne_reluflatten_softmax *InstancePtr);
u32 XDesne_reluflatten_softmax_InterruptGetStatus(XDesne_reluflatten_softmax *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
