// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xadd_bias_and_relu_flatten3_softmax.h"

extern XAdd_bias_and_relu_flatten3_softmax_Config XAdd_bias_and_relu_flatten3_softmax_ConfigTable[];

XAdd_bias_and_relu_flatten3_softmax_Config *XAdd_bias_and_relu_flatten3_softmax_LookupConfig(u16 DeviceId) {
	XAdd_bias_and_relu_flatten3_softmax_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XADD_BIAS_AND_RELU_FLATTEN3_SOFTMAX_NUM_INSTANCES; Index++) {
		if (XAdd_bias_and_relu_flatten3_softmax_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XAdd_bias_and_relu_flatten3_softmax_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XAdd_bias_and_relu_flatten3_softmax_Initialize(XAdd_bias_and_relu_flatten3_softmax *InstancePtr, u16 DeviceId) {
	XAdd_bias_and_relu_flatten3_softmax_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XAdd_bias_and_relu_flatten3_softmax_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XAdd_bias_and_relu_flatten3_softmax_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

