// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// CONTROL
// 0x0 : Control signals
//       bit 0  - ap_start (Read/Write/COH)
//       bit 1  - ap_done (Read/COR)
//       bit 2  - ap_idle (Read)
//       bit 3  - ap_ready (Read)
//       bit 7  - auto_restart (Read/Write)
//       others - reserved
// 0x4 : Global Interrupt Enable Register
//       bit 0  - Global Interrupt Enable (Read/Write)
//       others - reserved
// 0x8 : IP Interrupt Enable Register (Read/Write)
//       bit 0  - Channel 0 (ap_done)
//       bit 1  - Channel 1 (ap_ready)
//       others - reserved
// 0xc : IP Interrupt Status Register (Read/TOW)
//       bit 0  - Channel 0 (ap_done)
//       bit 1  - Channel 1 (ap_ready)
//       others - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XADD_BIAS_AND_RELU_FLATTEN2_CONTROL_ADDR_AP_CTRL 0x0
#define XADD_BIAS_AND_RELU_FLATTEN2_CONTROL_ADDR_GIE     0x4
#define XADD_BIAS_AND_RELU_FLATTEN2_CONTROL_ADDR_IER     0x8
#define XADD_BIAS_AND_RELU_FLATTEN2_CONTROL_ADDR_ISR     0xc

// INPUT
// 0x4000 ~
// 0x7fff : Memory 'mem_block1_dense' (4096 * 32b)
//          Word n : bit [31:0] - mem_block1_dense[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XADD_BIAS_AND_RELU_FLATTEN2_INPUT_ADDR_MEM_BLOCK1_DENSE_BASE 0x4000
#define XADD_BIAS_AND_RELU_FLATTEN2_INPUT_ADDR_MEM_BLOCK1_DENSE_HIGH 0x7fff
#define XADD_BIAS_AND_RELU_FLATTEN2_INPUT_WIDTH_MEM_BLOCK1_DENSE     32
#define XADD_BIAS_AND_RELU_FLATTEN2_INPUT_DEPTH_MEM_BLOCK1_DENSE     4096

// OUTPUT
// 0x4000 ~
// 0x7fff : Memory 'memblock1_dense' (4096 * 32b)
//          Word n : bit [31:0] - memblock1_dense[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XADD_BIAS_AND_RELU_FLATTEN2_OUTPUT_ADDR_MEMBLOCK1_DENSE_BASE 0x4000
#define XADD_BIAS_AND_RELU_FLATTEN2_OUTPUT_ADDR_MEMBLOCK1_DENSE_HIGH 0x7fff
#define XADD_BIAS_AND_RELU_FLATTEN2_OUTPUT_WIDTH_MEMBLOCK1_DENSE     32
#define XADD_BIAS_AND_RELU_FLATTEN2_OUTPUT_DEPTH_MEMBLOCK1_DENSE     4096

// parameter
// 0x4000 ~
// 0x7fff : Memory 'bd2' (4096 * 32b)
//          Word n : bit [31:0] - bd2[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XADD_BIAS_AND_RELU_FLATTEN2_PARAMETER_ADDR_BD2_BASE 0x4000
#define XADD_BIAS_AND_RELU_FLATTEN2_PARAMETER_ADDR_BD2_HIGH 0x7fff
#define XADD_BIAS_AND_RELU_FLATTEN2_PARAMETER_WIDTH_BD2     32
#define XADD_BIAS_AND_RELU_FLATTEN2_PARAMETER_DEPTH_BD2     4096

