// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XADD_BIAS_AND_RELU_FLATTEN2_H
#define XADD_BIAS_AND_RELU_FLATTEN2_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xadd_bias_and_relu_flatten2_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_BaseAddress;
    u32 Input_BaseAddress;
    u32 Output_BaseAddress;
    u32 Parameter_BaseAddress;
} XAdd_bias_and_relu_flatten2_Config;
#endif

typedef struct {
    u32 Control_BaseAddress;
    u32 Input_BaseAddress;
    u32 Output_BaseAddress;
    u32 Parameter_BaseAddress;
    u32 IsReady;
} XAdd_bias_and_relu_flatten2;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XAdd_bias_and_relu_flatten2_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XAdd_bias_and_relu_flatten2_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XAdd_bias_and_relu_flatten2_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XAdd_bias_and_relu_flatten2_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XAdd_bias_and_relu_flatten2_Initialize(XAdd_bias_and_relu_flatten2 *InstancePtr, u16 DeviceId);
XAdd_bias_and_relu_flatten2_Config* XAdd_bias_and_relu_flatten2_LookupConfig(u16 DeviceId);
int XAdd_bias_and_relu_flatten2_CfgInitialize(XAdd_bias_and_relu_flatten2 *InstancePtr, XAdd_bias_and_relu_flatten2_Config *ConfigPtr);
#else
int XAdd_bias_and_relu_flatten2_Initialize(XAdd_bias_and_relu_flatten2 *InstancePtr, const char* InstanceName);
int XAdd_bias_and_relu_flatten2_Release(XAdd_bias_and_relu_flatten2 *InstancePtr);
#endif

void XAdd_bias_and_relu_flatten2_Start(XAdd_bias_and_relu_flatten2 *InstancePtr);
u32 XAdd_bias_and_relu_flatten2_IsDone(XAdd_bias_and_relu_flatten2 *InstancePtr);
u32 XAdd_bias_and_relu_flatten2_IsIdle(XAdd_bias_and_relu_flatten2 *InstancePtr);
u32 XAdd_bias_and_relu_flatten2_IsReady(XAdd_bias_and_relu_flatten2 *InstancePtr);
void XAdd_bias_and_relu_flatten2_EnableAutoRestart(XAdd_bias_and_relu_flatten2 *InstancePtr);
void XAdd_bias_and_relu_flatten2_DisableAutoRestart(XAdd_bias_and_relu_flatten2 *InstancePtr);

u32 XAdd_bias_and_relu_flatten2_Get_mem_block1_dense_BaseAddress(XAdd_bias_and_relu_flatten2 *InstancePtr);
u32 XAdd_bias_and_relu_flatten2_Get_mem_block1_dense_HighAddress(XAdd_bias_and_relu_flatten2 *InstancePtr);
u32 XAdd_bias_and_relu_flatten2_Get_mem_block1_dense_TotalBytes(XAdd_bias_and_relu_flatten2 *InstancePtr);
u32 XAdd_bias_and_relu_flatten2_Get_mem_block1_dense_BitWidth(XAdd_bias_and_relu_flatten2 *InstancePtr);
u32 XAdd_bias_and_relu_flatten2_Get_mem_block1_dense_Depth(XAdd_bias_and_relu_flatten2 *InstancePtr);
u32 XAdd_bias_and_relu_flatten2_Write_mem_block1_dense_Words(XAdd_bias_and_relu_flatten2 *InstancePtr, int offset, int *data, int length);
u32 XAdd_bias_and_relu_flatten2_Read_mem_block1_dense_Words(XAdd_bias_and_relu_flatten2 *InstancePtr, int offset, int *data, int length);
u32 XAdd_bias_and_relu_flatten2_Write_mem_block1_dense_Bytes(XAdd_bias_and_relu_flatten2 *InstancePtr, int offset, char *data, int length);
u32 XAdd_bias_and_relu_flatten2_Read_mem_block1_dense_Bytes(XAdd_bias_and_relu_flatten2 *InstancePtr, int offset, char *data, int length);
u32 XAdd_bias_and_relu_flatten2_Get_memblock1_dense_BaseAddress(XAdd_bias_and_relu_flatten2 *InstancePtr);
u32 XAdd_bias_and_relu_flatten2_Get_memblock1_dense_HighAddress(XAdd_bias_and_relu_flatten2 *InstancePtr);
u32 XAdd_bias_and_relu_flatten2_Get_memblock1_dense_TotalBytes(XAdd_bias_and_relu_flatten2 *InstancePtr);
u32 XAdd_bias_and_relu_flatten2_Get_memblock1_dense_BitWidth(XAdd_bias_and_relu_flatten2 *InstancePtr);
u32 XAdd_bias_and_relu_flatten2_Get_memblock1_dense_Depth(XAdd_bias_and_relu_flatten2 *InstancePtr);
u32 XAdd_bias_and_relu_flatten2_Write_memblock1_dense_Words(XAdd_bias_and_relu_flatten2 *InstancePtr, int offset, int *data, int length);
u32 XAdd_bias_and_relu_flatten2_Read_memblock1_dense_Words(XAdd_bias_and_relu_flatten2 *InstancePtr, int offset, int *data, int length);
u32 XAdd_bias_and_relu_flatten2_Write_memblock1_dense_Bytes(XAdd_bias_and_relu_flatten2 *InstancePtr, int offset, char *data, int length);
u32 XAdd_bias_and_relu_flatten2_Read_memblock1_dense_Bytes(XAdd_bias_and_relu_flatten2 *InstancePtr, int offset, char *data, int length);
u32 XAdd_bias_and_relu_flatten2_Get_bd2_BaseAddress(XAdd_bias_and_relu_flatten2 *InstancePtr);
u32 XAdd_bias_and_relu_flatten2_Get_bd2_HighAddress(XAdd_bias_and_relu_flatten2 *InstancePtr);
u32 XAdd_bias_and_relu_flatten2_Get_bd2_TotalBytes(XAdd_bias_and_relu_flatten2 *InstancePtr);
u32 XAdd_bias_and_relu_flatten2_Get_bd2_BitWidth(XAdd_bias_and_relu_flatten2 *InstancePtr);
u32 XAdd_bias_and_relu_flatten2_Get_bd2_Depth(XAdd_bias_and_relu_flatten2 *InstancePtr);
u32 XAdd_bias_and_relu_flatten2_Write_bd2_Words(XAdd_bias_and_relu_flatten2 *InstancePtr, int offset, int *data, int length);
u32 XAdd_bias_and_relu_flatten2_Read_bd2_Words(XAdd_bias_and_relu_flatten2 *InstancePtr, int offset, int *data, int length);
u32 XAdd_bias_and_relu_flatten2_Write_bd2_Bytes(XAdd_bias_and_relu_flatten2 *InstancePtr, int offset, char *data, int length);
u32 XAdd_bias_and_relu_flatten2_Read_bd2_Bytes(XAdd_bias_and_relu_flatten2 *InstancePtr, int offset, char *data, int length);

void XAdd_bias_and_relu_flatten2_InterruptGlobalEnable(XAdd_bias_and_relu_flatten2 *InstancePtr);
void XAdd_bias_and_relu_flatten2_InterruptGlobalDisable(XAdd_bias_and_relu_flatten2 *InstancePtr);
void XAdd_bias_and_relu_flatten2_InterruptEnable(XAdd_bias_and_relu_flatten2 *InstancePtr, u32 Mask);
void XAdd_bias_and_relu_flatten2_InterruptDisable(XAdd_bias_and_relu_flatten2 *InstancePtr, u32 Mask);
void XAdd_bias_and_relu_flatten2_InterruptClear(XAdd_bias_and_relu_flatten2 *InstancePtr, u32 Mask);
u32 XAdd_bias_and_relu_flatten2_InterruptGetEnabled(XAdd_bias_and_relu_flatten2 *InstancePtr);
u32 XAdd_bias_and_relu_flatten2_InterruptGetStatus(XAdd_bias_and_relu_flatten2 *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
