// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// CONTROL
// 0x0 : Control signals
//       bit 0  - ap_start (Read/Write/COH)
//       bit 1  - ap_done (Read/COR)
//       bit 2  - ap_idle (Read)
//       bit 3  - ap_ready (Read)
//       bit 7  - auto_restart (Read/Write)
//       others - reserved
// 0x4 : Global Interrupt Enable Register
//       bit 0  - Global Interrupt Enable (Read/Write)
//       others - reserved
// 0x8 : IP Interrupt Enable Register (Read/Write)
//       bit 0  - Channel 0 (ap_done)
//       bit 1  - Channel 1 (ap_ready)
//       others - reserved
// 0xc : IP Interrupt Status Register (Read/TOW)
//       bit 0  - Channel 0 (ap_done)
//       bit 1  - Channel 1 (ap_ready)
//       others - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XSOFTMAX_CONTROL_ADDR_AP_CTRL 0x0
#define XSOFTMAX_CONTROL_ADDR_GIE     0x4
#define XSOFTMAX_CONTROL_ADDR_IER     0x8
#define XSOFTMAX_CONTROL_ADDR_ISR     0xc

// INPUT
// 0x1000 ~
// 0x1fff : Memory 'memblock2_dense' (1000 * 32b)
//          Word n : bit [31:0] - memblock2_dense[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XSOFTMAX_INPUT_ADDR_MEMBLOCK2_DENSE_BASE 0x1000
#define XSOFTMAX_INPUT_ADDR_MEMBLOCK2_DENSE_HIGH 0x1fff
#define XSOFTMAX_INPUT_WIDTH_MEMBLOCK2_DENSE     32
#define XSOFTMAX_INPUT_DEPTH_MEMBLOCK2_DENSE     1000

// OUTPUT
// 0x1000 ~
// 0x1fff : Memory 'class' (1000 * 32b)
//          Word n : bit [31:0] - class[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XSOFTMAX_OUTPUT_ADDR_CLASS_BASE 0x1000
#define XSOFTMAX_OUTPUT_ADDR_CLASS_HIGH 0x1fff
#define XSOFTMAX_OUTPUT_WIDTH_CLASS     32
#define XSOFTMAX_OUTPUT_DEPTH_CLASS     1000

// OUTPUT1
// 0x1000 ~
// 0x1fff : Memory 'result' (1000 * 32b)
//          Word n : bit [31:0] - result[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XSOFTMAX_OUTPUT1_ADDR_RESULT_BASE 0x1000
#define XSOFTMAX_OUTPUT1_ADDR_RESULT_HIGH 0x1fff
#define XSOFTMAX_OUTPUT1_WIDTH_RESULT     32
#define XSOFTMAX_OUTPUT1_DEPTH_RESULT     1000

