// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// CONTROL
// 0x0 : Control signals
//       bit 0  - ap_start (Read/Write/COH)
//       bit 1  - ap_done (Read/COR)
//       bit 2  - ap_idle (Read)
//       bit 3  - ap_ready (Read)
//       bit 7  - auto_restart (Read/Write)
//       others - reserved
// 0x4 : Global Interrupt Enable Register
//       bit 0  - Global Interrupt Enable (Read/Write)
//       others - reserved
// 0x8 : IP Interrupt Enable Register (Read/Write)
//       bit 0  - Channel 0 (ap_done)
//       bit 1  - Channel 1 (ap_ready)
//       others - reserved
// 0xc : IP Interrupt Status Register (Read/TOW)
//       bit 0  - Channel 0 (ap_done)
//       bit 1  - Channel 1 (ap_ready)
//       others - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDENSE_RELUFLATTEN_SOFTMAX_CONTROL_ADDR_AP_CTRL 0x0
#define XDENSE_RELUFLATTEN_SOFTMAX_CONTROL_ADDR_GIE     0x4
#define XDENSE_RELUFLATTEN_SOFTMAX_CONTROL_ADDR_IER     0x8
#define XDENSE_RELUFLATTEN_SOFTMAX_CONTROL_ADDR_ISR     0xc

// INPUT
// 0x20000 ~
// 0x3ffff : Memory 'mem_block1_dense' (25088 * 32b)
//           Word n : bit [31:0] - mem_block1_dense[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDENSE_RELUFLATTEN_SOFTMAX_INPUT_ADDR_MEM_BLOCK1_DENSE_BASE 0x20000
#define XDENSE_RELUFLATTEN_SOFTMAX_INPUT_ADDR_MEM_BLOCK1_DENSE_HIGH 0x3ffff
#define XDENSE_RELUFLATTEN_SOFTMAX_INPUT_WIDTH_MEM_BLOCK1_DENSE     32
#define XDENSE_RELUFLATTEN_SOFTMAX_INPUT_DEPTH_MEM_BLOCK1_DENSE     25088

// OUTPUT
// 0x1000 ~
// 0x1fff : Memory 'class' (1000 * 32b)
//          Word n : bit [31:0] - class[n]
// 0x2000 ~
// 0x2fff : Memory 'result' (1000 * 32b)
//          Word n : bit [31:0] - result[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDENSE_RELUFLATTEN_SOFTMAX_OUTPUT_ADDR_CLASS_BASE  0x1000
#define XDENSE_RELUFLATTEN_SOFTMAX_OUTPUT_ADDR_CLASS_HIGH  0x1fff
#define XDENSE_RELUFLATTEN_SOFTMAX_OUTPUT_WIDTH_CLASS      32
#define XDENSE_RELUFLATTEN_SOFTMAX_OUTPUT_DEPTH_CLASS      1000
#define XDENSE_RELUFLATTEN_SOFTMAX_OUTPUT_ADDR_RESULT_BASE 0x2000
#define XDENSE_RELUFLATTEN_SOFTMAX_OUTPUT_ADDR_RESULT_HIGH 0x2fff
#define XDENSE_RELUFLATTEN_SOFTMAX_OUTPUT_WIDTH_RESULT     32
#define XDENSE_RELUFLATTEN_SOFTMAX_OUTPUT_DEPTH_RESULT     1000

// parameter
// 0x4000 ~
// 0x7fff : Memory 'bd1' (4096 * 32b)
//          Word n : bit [31:0] - bd1[n]
// 0x8000 ~
// 0xbfff : Memory 'bd2' (4096 * 32b)
//          Word n : bit [31:0] - bd2[n]
// 0xc000 ~
// 0xcfff : Memory 'bd3' (1000 * 32b)
//          Word n : bit [31:0] - bd3[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDENSE_RELUFLATTEN_SOFTMAX_PARAMETER_ADDR_BD1_BASE 0x4000
#define XDENSE_RELUFLATTEN_SOFTMAX_PARAMETER_ADDR_BD1_HIGH 0x7fff
#define XDENSE_RELUFLATTEN_SOFTMAX_PARAMETER_WIDTH_BD1     32
#define XDENSE_RELUFLATTEN_SOFTMAX_PARAMETER_DEPTH_BD1     4096
#define XDENSE_RELUFLATTEN_SOFTMAX_PARAMETER_ADDR_BD2_BASE 0x8000
#define XDENSE_RELUFLATTEN_SOFTMAX_PARAMETER_ADDR_BD2_HIGH 0xbfff
#define XDENSE_RELUFLATTEN_SOFTMAX_PARAMETER_WIDTH_BD2     32
#define XDENSE_RELUFLATTEN_SOFTMAX_PARAMETER_DEPTH_BD2     4096
#define XDENSE_RELUFLATTEN_SOFTMAX_PARAMETER_ADDR_BD3_BASE 0xc000
#define XDENSE_RELUFLATTEN_SOFTMAX_PARAMETER_ADDR_BD3_HIGH 0xcfff
#define XDENSE_RELUFLATTEN_SOFTMAX_PARAMETER_WIDTH_BD3     32
#define XDENSE_RELUFLATTEN_SOFTMAX_PARAMETER_DEPTH_BD3     1000

